version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: social_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
